Fix buffer overruns on 64-bit architectures caused by broken redefinition of size_t. Removed other spurious redefines/undefines that should no longer be necessary.
Rev: src/modules/_Image_JPEG/image_jpeg.c:1.74