Fixed some compilation errors caused by recent commits.
Also fixes API issue.

Rev: lib/modules/Locale.pmod/Charset.pmod/Tables.pmod/iso88591.pmod:1.7